#/*-----------------------------------------------------------
# *
# * SWE2007: Software Experiment 2 (FALL 2018)
# *
# * Skeleton code for PA#1
# * 
# * September 17, 2018.
# * Computer Network Lab, Sungkyunkwan University
# *
# * Student Id   : 2017310528
# * Student Name : 신재광
# *
# *-----------------------------------------------------------
# */

CC		= gcc
CFLAGS	= -g -O -Wall
LDFLAGS	=
RM		= rm

CSRCS	= main.c indexBuilder.c indexPrinter.c
TARGET	= indexBP
OBJECTS	= $(CSRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
		$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.c.o:
		$(CC) $(CFLAGS) -c $< -o $@

clean:
		$(RM) -f $(OBJECTS) $(TARGET) *~
